# Generated by Django 4.2.20 on 2025-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpic', models.ImageField(upload_to='booktest')),
            ],
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='atitle',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
    ]
