# Generated by Django 4.2.20 on 2025-05-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_pictest_alter_areainfo_atitle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pictest',
            table='pictest',
        ),
    ]
